# Generated by Django 4.2 on 2023-04-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_books_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='post_author',
        ),
    ]
